version: '3.8'

services:
  app:
    networks:
      - nasa-largest-picture-service
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      HTTP_ADDR: ":8080"
      NASA_API_KEY: "dwCFy0H309Cz1n6f5O0MuQUdcpoccjszuBemFQ8G"
      DSN: "postgresql://postgres:postgres@postgres/postgres?sslmode=disable"
    command: ["./wait-for-it.sh", "postgres:5433", "--timeout=60", "--", "./app"]

  postgres:
    networks:
      - nasa-largest-picture-service
    restart: always
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./internal/pg/data:/var/lib/postgresql/data

networks:
  nasa-largest-picture-service:
